/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 tron.gltf
Author: marajoos (https://sketchfab.com/marajoos)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tron-character-6be459f7b8214790965e509144e3221a
Title: Tron Character
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tron.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['TronCharacter_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
    </group>
  )
}

useGLTF.preload('/tron.gltf')
